title: '@thetonyrom'
email: thetonyrom@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Tony Rom's blog

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thetonyrom.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: thetonyrom
github_username:  thetonyrom

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Gtag
gtag: UA-109555278-1
